version: "3.8"

volumes:
  mysql_data:
  elasticsearch_volume:

services:
  mysqldb:
    build: backend/db
    env_file:
      - "backend/db/db.env"
    ports:
      - "8989:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend/was
    command: >
      bash -c  "python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend/was:/app
    depends_on:
      mysqldb:
        condition: service_healthy

  frontend:
    build: ./frontend
    command: ["npm", "start"]
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app